### ISSUE TITLE
BUG: Do not working with list 

### ISSUE THREAD

**Issue by Breate** [neuroglia-io/asyncapi#13]
## Description
Serialization of List / Arrays not working

## How to reproduce?
i try to serialize next model

public class ActivityCreateModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ActivityType { get; set; }
        public DateTime ActivityTime { get; set; }
        public Guid? CompanyId { get; set; }
        public string Shortcut { get; set; }
        public Guid UserInformationId { get; set; }
        public Guid? CreatorId { get; set; }
        public IList< ActivityPropertyViewModel > Properties { get; set; }
    }

## Expected behavior
Prepared AsyncApi document 

## Actual behavior
`
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Neuroglia.AsyncApi.JsonSchemaExtensions.GenerateExampleArrayFor(JsonSchema schema, Boolean requiredPropertiesOnly)
   at Neuroglia.AsyncApi.JsonSchemaExtensions.GenerateExample(JsonSchema schema, String name, Boolean requiredPropertiesOnly)
   at Neuroglia.AsyncApi.JsonSchemaExtensions.GenerateExampleObjectFor(JsonSchema schema, Boolean requiredPropertiesOnly)
   at Neuroglia.AsyncApi.JsonSchemaExtensions.GenerateExample(JsonSchema schema, String name, Boolean requiredPropertiesOnly)
   at Neuroglia.AsyncApi.JsonSchemaExtensions.GenerateExamples(JsonSchema schema)
   at Neuroglia.AsyncApi.Services.Generators.AsyncApiDocumentGenerator.ConfigureOperationMessageFor(IMessageDefinitionBuilder messageBuilder, OperationAttribute operation, MethodInfo operationMethod, AsyncApiDocumentGenerationOptions options)
   at Neuroglia.AsyncApi.Services.Generators.AsyncApiDocumentGenerator.<>c__DisplayClass7_1.<ConfigureChannelForAsync>b__2(IMessageDefinitionBuilder messageBuilder)
   at Neuroglia.AsyncApi.Services.FluentBuilders.OperationDefinitionBuilder.UseMessage(Action`1 setup)
   at Neuroglia.AsyncApi.Services.Generators.AsyncApiDocumentGenerator.<>c__DisplayClass7_1.<ConfigureChannelForAsync>b__1(IOperationDefinitionBuilder operationBuilder)
   at Neuroglia.AsyncApi.Services.FluentBuilders.ChannelDefinitionBuilder.DefineOperation(OperationType type, Action`1 setup)
   at Neuroglia.AsyncApi.Services.Generators.AsyncApiDocumentGenerator.<>c__DisplayClass7_0.<ConfigureChannelForAsync>b__0(IChannelDefinitionBuilder channelBuilder)
   at Neuroglia.AsyncApi.Services.FluentBuilders.AsyncApiDocumentBuilder.UseChannel(String name, Action`1 setup)
   at Neuroglia.AsyncApi.Services.Generators.AsyncApiDocumentGenerator.ConfigureChannelForAsync(IAsyncApiDocumentBuilder builder, ChannelAttribute channel, List`1 methods, AsyncApiDocumentGenerationOptions options, CancellationToken cancellationToken)
   at Neuroglia.AsyncApi.Services.Generators.AsyncApiDocumentGenerator.GenerateDocumentForAsync(Type type, AsyncApiDocumentGenerationOptions options, CancellationToken cancellationToken)
   at Neuroglia.AsyncApi.Services.Generators.AsyncApiDocumentGenerator.GenerateAsync(IEnumerable`1 markupTypes, AsyncApiDocumentGenerationOptions options)
   at Neuroglia.AsyncApi.Services.AsyncApiDocumentProvider.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

`

**Comment by cdavernas** [comment]
Sorry for the late reply, I'm very busy with other OSS projects. Will have a look into it this week ;)

**Comment by aman-agrawal-coolblue** [comment]
Hello, just run into this myself yesterday, any updates on it?

**Comment by cdavernas** [comment]
Hello @Breate and hello @aman-agrawal-coolblue!

Sorry for the late replay, last year has been crazy for me!

Your problem has been fixed, along with many others, in https://github.com/neuroglia-io/asyncapi/releases/tag/v2.6.0!

Hope you enjoy the revamp of the UI, too!
